### ISSUE TITLE
Build instructions (Fedora)

### ISSUE THREAD

**Issue by stevenroose** [jeena/FeedTheMonkey#6]
I'm trying to build this project on Fedora, but I got no clue where to start. There's only C++ source and header files, no makefile or anything.

Thanks!

**Comment by jeena** [comment]
Hi, it is a Qt project, so if you have QtCreator installed you can open the project by opening the file `FeedTheMonkey.pro` in QtCreator. Then you can press the `play` button to compile and start it.

If you don't have QtCreator installed then you will need to install it is a bit harder because then you will need to have all the necessary libs installed, a compiler and `qmake` because this is a Qt project I used `qmake` which then creates a Makefile.

**Comment by stevenroose** [comment]
I still don't get this working without installing QtCreator. Why don't you provide a makefile with it?

**Comment by jeena** [comment]
So how this works is that `qmake` is used to generate a `Makefile` from the `FeedTheMonkey.pro` file which is then used to compile and link the project. I can't add the Makefile itself because it is customized to the environment where it is running.

The Makefiles that qmake produces are tailored to the particular platform where it is run from based on qmake project files. This way one set of build instructions can be used to create build instructions on different operating systems. qmake supports code generation for the following operating systems: Linux, Apple Mac OS X, Symbian, Microsoft Windows and Microsoft Windows CE.

Thus you need to use qmake to generate a Makefile on your computer and then you will be able to compile it, if you have installed all the dependencies too (which are stated in the project file too.)

**Comment by stevenroose** [comment]
Hmm ok, that makes sense to me :)

I can't currently find how to install qmake, but I will probably find that
once I Google it..

**Comment by jeena** [comment]
I guess the by far easiest way would be to use the installer the Qt project provides which you can find here: http://www.qt.io/download-open-source/ and then to install Qt 5.5 with it. This will also install QtCreator in addition to all libraries which this project depends on and qmake.

In a longer run I'd like to provide just a RPM to download, the problem is that I'm using a lot of the stuff which can be found only in Qt 5.4 and later which is not available on for example Debian (I'm not sure about Fedora, which version is used there). So even if I create a package people won't be able to install it because of the dependencies to a fairly new version of Qt which is not available in the mainstream distros. But this hopefully will change in the future.
